AWSTemplateFormatVersion: '2010-09-09'
Resources:
  LaunchTemplateStep:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        IamInstanceProfile:
          Arn: arn:aws:iam::133171059739:instance-profile/role_infra_dev_cloudops
        ImageId: ami-06b21ccaeff8cd686
        InstanceMarketOptions:
          MarketType: spot
        InstanceType: t3a.small
        TagSpecifications:  # Move TagSpecifications inside LaunchTemplateData
          - ResourceType: "instance"  # Correct ResourceType
            Tags:
              - Key: "Name"
                Value: "Ec2Step"
              - Key: "CostCategory"
                Value: "INFRA - DEV"
              - Key: "RunType"
                Value: "On Demand"
              - Key: "AccountingCategory"
                Value: "Infrastructure"
      VersionDescription: "Init Version"

  AutoscalingGroupStep:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: ASG-Step
      AvailabilityZones:
        - us-east-1a
        - us-east-1b
      CapacityRebalance: True
      DefaultInstanceWarmup: 300
      DesiredCapacity: 1
      HealthCheckGracePeriod: 300
      HealthCheckType: EC2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplateStep
        Version: 1
      MaxSize: 4
      MinSize: 1
      VPCZoneIdentifier:
        - subnet-0e33d32ee28a04189
        - subnet-09c3a829407d43097

  AutoScalingPolicyStep:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AdjustmentType: ExactCapacity
      AutoScalingGroupName: !Ref AutoscalingGroupStep  # Reference the AutoscalingGroup
      MetricAggregationType: Average
      PolicyType: StepScaling
      StepAdjustments:
        - MetricIntervalLowerBound: '0'
          MetricIntervalUpperBound: '20'
          ScalingAdjustment: '2'
        - MetricIntervalLowerBound: '20'
          MetricIntervalUpperBound: '40'
          ScalingAdjustment: '3'
        - MetricIntervalLowerBound: '40'
          ScalingAdjustment: '4'



  AverageAutoscaleCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "StepScaling-AverageCPUAlarm"
      AlarmDescription: "Alarm when CPU exceeds 10%"
      Namespace: "AWS/EC2"
      MetricName: "CPUUtilization"
      Dimensions:
        - Name: "AutoScalingGroupName"
          Value: !Ref AutoscalingGroupStep
      Statistic: "Average"
      Period: 300
      EvaluationPeriods: 3
      Threshold: 50
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - !Ref AutoScalingPolicyStep
      OKActions:
        - !Ref AutoScalingPolicyStep
      TreatMissingData: "notBreaching"